[project]
name = "mumulmumul"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.121.3",
    "jupyter>=1.1.1",
    "langchain>=1.0.8",
    "langgraph>=1.0.3",
    "streamlit>=1.51.0",
]
